// Domain enums and row types that used to be generated by Prisma.
// Each enum is a const object (usable as a value, e.g. with z.nativeEnum)
// plus a string-union type of the same name.

export const Role = { ADMIN: "ADMIN", USER: "USER", AI: "AI" } as const;
export type Role = (typeof Role)[keyof typeof Role];

export const Gender = { MALE: "MALE", FEMALE: "FEMALE" } as const;
export type Gender = (typeof Gender)[keyof typeof Gender];

export const Difficulty = { EASY: "EASY", MODERATE: "MODERATE", HARD: "HARD" } as const;
export type Difficulty = (typeof Difficulty)[keyof typeof Difficulty];

export const DiseaseType = {
    OBESITY: "OBESITY",
    HYPERTENSION: "HYPERTENSION",
    DIABETES: "DIABETES",
    SMOKING: "SMOKING",
    ALCOHOL: "ALCOHOL",
    STRESS: "STRESS",
} as const;
export type DiseaseType = (typeof DiseaseType)[keyof typeof DiseaseType];

export const DayOfWeekType = {
    MONDAY: "MONDAY",
    TUESDAY: "TUESDAY",
    WEDNESDAY: "WEDNESDAY",
    THURSDAY: "THURSDAY",
    FRIDAY: "FRIDAY",
    SATURDAY: "SATURDAY",
    SUNDAY: "SUNDAY",
} as const;
export type DayOfWeekType = (typeof DayOfWeekType)[keyof typeof DayOfWeekType];

export const MealType = { BREAKFAST: "BREAKFAST", LUNCH: "LUNCH", DINNER: "DINNER" } as const;
export type MealType = (typeof MealType)[keyof typeof MealType];

export const CharacterStage = {
    SPROUT: "SPROUT",
    GROWTH: "GROWTH",
    SKILLED: "SKILLED",
    CHAMPION: "CHAMPION",
    MASTER: "MASTER",
} as const;
export type CharacterStage = (typeof CharacterStage)[keyof typeof CharacterStage];

export const HeroStyle = { IRON: "IRON", DARK: "DARK", SPIDER: "SPIDER" } as const;
export type HeroStyle = (typeof HeroStyle)[keyof typeof HeroStyle];

export const PlanType = { NUTRITION: "NUTRITION", EXERCISE: "EXERCISE" } as const;
export type PlanType = (typeof PlanType)[keyof typeof PlanType];

/** Stored nutrition summary row (numeric percentages). */
export interface NutritionSummary {
    id: string;
    vitaminA: number;
    vitaminC: number;
    vitaminD: number;
    calcium: number;
    protein: number;
    carbohydrates: number;
    fat: number;
    fiber: number;
    sugar: number;
    sodium: number;
    cholesterol: number;
    createdAt: string;
    updatedAt: string;
}
